Add deactivate API to ruby bindings (bsc#1202705)
SUSE/connect-ng pull request #153
Opened 2022-09-21 11:14 UTC by skazi0

Existing functionalities used by CLI were exposed and can be called from ruby clients.

Closes #148

2022-10-17 13:04 UTC, lslezak approved these changes
Yes, this is what we need in YaST, thank you!

Just let me know in which version it will be released.

2022-11-16 17:39 UTC, mssola approved these changes
I don't have a way to test this, to be honest, but it looks good code-wise.

@djoreilly you are also listed as a reviewer on this, could you take a look? Thanks!

2022-11-17 14:42 UTC, djoreilly requested changes

2022-11-17 14:42 UTC, djoreilly commented on yast/lib/suse/connect/yast.rb
> +        _set_verify_callback(client_params[:verify_callback])
the indentation looks wrong here. I'll look into it

2022-11-17 15:13 UTC, djoreilly commented
Here's how I tested this. Downloaded rpms with browswer from https://build.opensuse.org/package/binaries/home:jzerebecki:CI:target:SUSE:connect-ng:PR-153/suseconnect-ng/openSUSE_Leap_15.3

mkdir /tmp/rpms
mv ~/Downloads/suseconne*rpm ~/Downloads/libsuseconnect-0.0.0_git.c72c299-lp153.20.1.x86_64.rpm /tmp/rpms/

docker run -it -v /tmp/rpms:/rpms --name test-pr153 registry.suse.com/bci/bci-base bash

    zypper rm -y container-suseconnect
    zypper in /rpms/*
  
    SUSEConnect -r ...
    SUSEConnect -p sle-module-containers/15.4/x86_64
  
    zypper in ruby
    irb
        require "suse/connect"
        p = OpenStruct.new(arch: "x86_64", identifier: "sle-module-containers", version: "15.4")
        SUSE::Connect::YaST.deactivate_product(p)
        # check SUSEConnect --status-text in another console
        SUSE::Connect::YaST.deactivate_system()
        # check SUSEConnect --status-text in another console

2022-12-13 12:48 UTC, digitaltom commented
Is there a reason for this not being merged yet?

2022-12-13 13:24 UTC, djoreilly commented
> Is there a reason for this not being merged yet?

no - it just needed some reviews. I think it's okay to merge now.

2022-12-13 13:36 UTC, merged

2022-12-15 15:36 UTC, lslezak commented
Thank you! :+1: