Add package_search API wrapper
SUSE/connect-ng pull request #83
Opened 2021-10-25 12:28 UTC by skazi0

2021-11-08 15:14 UTC, djoreilly requested changes

2021-11-08 15:14 UTC, djoreilly commented on testdata/package_search.json
> +{
I think we should add tests here

2021-11-09 21:13 UTC, skazi0 commented on testdata/package_search.json
> +{
done

2021-11-10 09:23 UTC, djoreilly approved these changes
lgtm

2021-11-10 09:57 UTC, merged